"""add name to spectrum

Revision ID: 11504d1feb38
Revises: b51beec5b08a
Create Date: 2025-07-08 21:11:41.266084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11504d1feb38'
down_revision: Union[str, None] = 'b51beec5b08a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spectra', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spectra', 'name')
    # ### end Alembic commands ###
