"""add status session

Revision ID: c06bf1d234db
Revises: c91a6df5c53e
Create Date: 2025-07-09 19:00:54.384900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06bf1d234db'
down_revision: Union[str, None] = 'c91a6df5c53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE celerystatus AS ENUM ('PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'RETRY')")
    op.add_column('sessions',
        sa.Column('processing_status', sa.Enum('PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'RETRY', name='celerystatus'), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'processing_status')
    # ### end Alembic commands ###
