name: Build AleDev to Docker Hub

run-name: "Build and push Docker images for ${{ github.ref_name }} by ${{ github.actor }}"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run backend tests
      run: |
        echo "Тесты бэкенда пока отключены. Возвращаем успешный статус."

    - name: Run frontend tests
      run: |
        echo "Тесты фронтенда пока отключены. Возвращаем успешный статус."

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Export ENV_VARS
      run: |
        printf "%s\n" "${{ secrets.ENV_ALEDEV_VARS }}" | while IFS= read -r line; do
          if [[ ! -z "$line" && "$line" != \#* ]]; then
            echo "$line" >> $GITHUB_ENV
          fi
        done

    - name: Build and push backend image
      run: |
        docker build -t aleksioprime/hyperspectrus-back:latest ./web/back
        docker push aleksioprime/hyperspectrus-back:latest

    - name: Build and push frontend image
      run: |
        docker build --target prod \
          --build-arg VITE_LOGGING=0 \
          --build-arg VITE_SERVICE_URL=$VITE_SERVICE_URL \
          -t aleksioprime/hyperspectrus-front:latest ./web/front

        docker push aleksioprime/hyperspectrus-front:latest
